baseurl = "https://peertube-viewer.com"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "Peertube Viewer"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
enableEmoji=true

[Params]
  subtitle = "Lightweight cli browser for Peertube"
  logo = "peertube-viewer-logo.svg"
  favicon = "peertube-viewer-logo.svg"
  dateFormat = "January 2, 2006"
  commit = false
  rssContent = "posts"
  gitlabLink = "https://gitlab.com/peertube-viewer/peertube-viewer-rs"
  comments = true

[Author]
  name = "Guédon Sosthène"
  gitlab = "peertube-viewer"
  github = "peertube-viewer"
  mail = "dev@peertube.com"


[[menu.main]]
    name = "News"
    url = "/posts"
    weight = 1
    params = { icon = "fa fa-newspaper" }

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    params = { icon = "fa fa-info-circle" }

[[menu.main]]
    name = "Download"
    url = "/download"
    weight = 3
    params = { icon = "fa fa-download" }

[[menu.main]]
    name = "Documentation"
    url = "https://docs.peertube-viewer.com"
    weight = 4
    params = { icon = "fa fa-book" }

[markup.goldmark.renderer]
  unsafe= true
